version: '3'
services:
  db:
    container_name: world-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/db:/docker-entrypoint-initdb.d

