/*
 * This file is generated by jOOQ.
 */
package com.aytdm.springbootjooq.domain.db.world;


import com.aytdm.springbootjooq.domain.db.world.tables.City;
import com.aytdm.springbootjooq.domain.db.world.tables.Country;
import com.aytdm.springbootjooq.domain.db.world.tables.Countrylanguage;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in world
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>world.city</code>.
     */
    public static final City CITY = com.aytdm.springbootjooq.domain.db.world.tables.City.CITY;

    /**
     * The table <code>world.country</code>.
     */
    public static final Country COUNTRY = com.aytdm.springbootjooq.domain.db.world.tables.Country.COUNTRY;

    /**
     * The table <code>world.countrylanguage</code>.
     */
    public static final Countrylanguage COUNTRYLANGUAGE = com.aytdm.springbootjooq.domain.db.world.tables.Countrylanguage.COUNTRYLANGUAGE;
}
